Richhandler suppress for #1836
Textualize/rich pull request #1858
Opened 2022-01-21 22:40 UTC by daddycocoaman

## Type of changes

- [ ] Bug fix
- [x] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

This PR adds the `suppress` functionality for Traceback to Rich Handler as well. The new `tracebacks_suppress` parameter is passed to the `Traceback` object created when `rich_tracebacks=True`.

One issue I had was creating a test. The test for Traceback suppress only counts the length of `suppress` after the modules/paths resolves. For this test, I tried to `emit` a custom `LogRecord` but I think the way Traceback handles rendering suppressed messages isn't compatible with an non-existent file. In other words, to ensure `RichHandler(console=console, rich_tracebacks=True, tracebacks_suppress=["foo.bar"])` is properly tested, an actual `foo` file should exist but I'm not sure how you want to handle extra files in the `tests` folder. I also tried supressing `pytest` but failed at that too.

2022-01-25 16:11 UTC, willmcgugan requested changes
I'm happy with not writing an explicit test for this. It's such a small surface area for any faults.

Just a couple requests re doc.

2022-01-25 16:11 UTC, willmcgugan commented on docs/source/logging.rst
> +        handlers=[RichHandler(rich_tracebacks=True, tracebacks_suppress)]
Did you mean?

```python
tracebacks_suppress=[click]
```

2022-01-25 16:11 UTC, willmcgugan commented on docs/source/logging.rst
> +If you are working with a framework (click, django etc), you may only be interested in seeing the code from your own application within the traceback. You can exclude framework code by setting the `s
Could you update this to refer to the RichHandler.

2022-02-11 11:16 UTC, willmcgugan approved these changes

2022-02-11 11:28 UTC, willmcgugan commented
I think black was updated since you did this. Would you mind reformatting? And then should be good to go.

2022-02-22 02:26 UTC, daddycocoaman commented
> I think black was updated since you did this. Would you mind reformatting? And then should be good to go.

Sorry for the delay...haven't been paying attention to my GH feed lately. I've updated as requested.

2022-02-27 10:58 UTC, willmcgugan commented
Thanks!

2022-02-27 10:58 UTC, merged