Expose diagnose.report as a function
Textualize/rich pull request #1917
Opened 2022-02-04 14:10 UTC by darrenburns

## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Adds `diagnose.report` function. Also adds some additional information from env vars if the user is using Jupyter, that might help convey what platform they're using if they don't specify in the bug report.

I've added the file as an omission to coverage reporting since it's only used for debug purposes.

2022-02-04 14:41 UTC, willmcgugan commented
Can I see an example of the report?

2022-02-04 14:45 UTC, darrenburns commented
@willmcgugan Added the output to the original post

2022-02-04 14:59 UTC, willmcgugan requested changes
I think it may be worth adding some additional env vars. Not quite everything, since users might have issues re privacy.

In addition to the Jupyter ones, I would add:

```
TERM
COLORTERM
CLICOLOR
NO_COLOR
TERM_PROGRAM
COLUMNS
LINES
```

Maybe extract those to a dict and pretty print them with

```python
Panel(Pretty(env_vars))
```

2022-02-04 14:59 UTC, willmcgugan commented on rich/diagnose.py
> +if __name__ == "__main__":  # pragma: no cover
Maybe also in invoke the report from the ``__main__`` block so that `python -m rich.diagnose` give the same info.

2022-02-04 14:59 UTC, willmcgugan commented on rich/diagnose.py
> +            Panel(
Can you add `panel.fit` to remove superfluous characters.

2022-02-04 14:59 UTC, willmcgugan commented on .github/ISSUE_TEMPLATE/bug_report.md
> +python -c "from rich.diagnose import report; report()"
Let's keep the original (less to cut and paste).

```
python -m rich.diagnose
```

2022-02-04 15:15 UTC, darrenburns commented
Will do

2022-02-07 10:08 UTC, darrenburns commented
```
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'iTerm.app',   │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
```

2022-02-07 10:50 UTC, willmcgugan reviewed
Great!

2022-02-07 10:50 UTC, merged