feat: optional RichHandler keywords
Textualize/rich pull request #1919
Opened 2022-02-04 21:49 UTC by aaronst

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [ ] I accept that @willmcgugan may be pedantic in the code review.

## Description

Add an optional `keywords` parameter to `RichHandler` to use instead of `RichHandler.KEYWORDS`.

2022-02-04 22:21 UTC, aaronst commented on rich/logging.py
> +        elif self.KEYWORDS:
Tried to keep changes minimal, `render_message()` will first check to see if `self.keywords` is set, and fall back on `self.KEYWORDS` if it's not.

2022-02-11 17:39 UTC, aaronst commented on rich/logging.py
> +        if self.keywords:
Yeah makes sense, good idea! I'll make the changes now.

2022-02-11 19:20 UTC, aaronst commented
@willmcgugan, a couple files that I didn't touch in this PR were failing the automated `black` check, so I got those fixed. I'm not sure what to do about this `mypy` error though, I thought it was a difference between `List` and `Iterable`, but it doesn't like that `self.keywords` is `Optional`.

2022-02-11 20:23 UTC, aaronst commented
> @willmcgugan, a couple files that I didn't touch in this PR were failing the automated `black` check, so I got those fixed. I'm not sure what to do about this `mypy` error though, I thought it was a difference between `List` and `Iterable`, but it doesn't like that `self.keywords` is `Optional`.

So turns out it was actually the `Optional` on `self.KEYWORDS` that `mypy` didn't like. I removed it in the latest commit, but if we need to keep it `Optional` I can change the logic to something like:
```python
if self.keywords is None:
    if self.KEYWORDS is not None:
        message_text.highlight_words(self.KEYWORDS, "logging.keyword")
else:
    message_text.highlight_words(self.keywords, "logging.keyword")
```

2022-02-13 15:43 UTC, willmcgugan requested changes

2022-02-13 15:43 UTC, willmcgugan commented on rich/logging.py
> +    KEYWORDS: ClassVar[List[str]] = [
The typing can't be changed now. Since its been optional since day one, people may have reasonably set it to None for no keywords.

2022-02-13 15:43 UTC, willmcgugan commented on rich/logging.py
> +        message_text.highlight_words(
How about this, to account for KEYWORDS being Optional?

```python
if keywords is None:
    keywords = self.KEYWORDS
if keywords:
    message_text.highlight_words(keywords, "logging.keyword")
```

2022-02-27 10:28 UTC, willmcgugan approved these changes

2022-02-27 10:28 UTC, willmcgugan commented
Thanks.

2022-02-27 10:28 UTC, merged