Handle recording on legacy mode Windows consoles
Textualize/rich pull request #2066
Opened 2022-03-15 11:05 UTC by darrenburns

## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Console.record=True was only being handled inside `_render_buffer`, which was not called on legacy mode consoles.

I've extracted the code for recording the buffer out of this method, to ensure it gets called regardless of environment.

2022-03-15 13:45 UTC, willmcgugan requested changes

2022-03-15 13:45 UTC, willmcgugan commented on rich/console.py
> +                            stdout_num = sys.stdout.fileno()
These probably don't need to be in a try except blog. Suggest replacing them with constants. `pty.STDOUT_FILENO` and `pty.STDERR_FILENO` contain the values so they don't need to be hard coded.

2022-03-16 09:49 UTC, willmcgugan approved these changes
LGTM

2022-03-16 09:59 UTC, darrenburns commented
@willmcgugan `pty` module doesn't work on Windows. Has a comment at the top of it too saying it's only tested on Unix and MacOS.

2022-03-18 16:45 UTC, willmcgugan approved these changes

2022-03-18 16:45 UTC, merged