[progress] The `total` we pass to a Progress renderable can now be `None`
Textualize/rich pull request #2166
Opened 2022-04-05 11:54 UTC by DrBenton

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [ ] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

2022-04-06 10:29 UTC, DrBenton commented on tests/test_progress.py
> -from rich.progress_bar import ProgressBar
only changed these imports in order to pass the `isort` part of the pre-commit hook :slightly_smiling_face:

2022-04-06 10:32 UTC, DrBenton commented on rich/progress.py
> +from .console import Console, Group, JustifyMethod, RenderableType
`isort` doing its things :slightly_smiling_face:

2022-04-06 10:32 UTC, DrBenton commented on rich/progress.py
> +            total=max(0, task.total) if task.total is not None else None,
I had to add loads of `if task.total is not None else` here and there, now that this "total" can be `None`

2022-04-06 13:06 UTC, willmcgugan commented
Making total `None` may qualify as a breaking change, but the alternatives don't seem much better...

What does a progress bar with default settings display when `total` is `None` now? Can I have a screenshot please.

2022-04-06 15:47 UTC, willmcgugan commented
I think what we might have to do is replace that TextColumn with the percentage, with a column that displays either the percentage OR iterations per second. I'm pretty sure that is what tqdm does.

The ETA should probably not display anything if there is no total.

Basically, the user should get something that broadly does what they would expect, given the constraints. Suggest analysing what tqdm does here.

2022-04-13 10:16 UTC, DrBenton commented
@willmcgugan hopefully this commit addresses your comment :crossed_fingers:  :slightly_smiling_face: : [f41bda6](https://github.com/Textualize/rich/pull/2166/commits/f41bda6de0b3b62541d9c66ef3582b3d1d107c30)

The progress bar in action:
![progress-bar-with-none-total-(4)](https://user-images.githubusercontent.com/722388/163156839-17e74062-e688-4926-8096-31bf37fb5d87.gif)

2022-04-13 14:08 UTC, willmcgugan requested changes
Great! Couple of small requests.

2022-04-13 14:08 UTC, willmcgugan commented on rich/progress.py
> +        transient=False,
I'm assuming the code below was for testing. Can you restore this so that `progress -m rich.progress` show a demonstration of multiple progress bars.

2022-04-14 15:35 UTC, DrBenton commented
Wooops, sorry @willmcgugan  for the mess in the `if __name__ == "__main__":` part of the "progress.py" module - I should have reviewed myself before requesting your review again! :sweat: 

I amended the commit, hopefully addressing your 2 comments: d2830c89b7a91631a :crossed_fingers:

2022-04-14 15:38 UTC, willmcgugan approved these changes
LGTM

2022-04-14 15:38 UTC, merged