add README.fa.md (Farsi Readme)
Textualize/rich pull request #2264
Opened 2022-05-08 15:32 UTC by motahharm

## Type of changes

- [x] Documentation / docstrings

## Checklist

- [x] I translated README to Persian or Farsi language.
- [x] I added ` • [فارسی readme](https://github.com/willmcgugan/rich/blob/master/README.fa.md)` in other READMEs.

## Description

Hi👋
I created README.fa.md and translated it.
then I added `فارسی readme` link to other READMEs.

2022-05-08 20:35 UTC, Msameim181 commented on README.fa.md
> +برای اضافه کردن راحت خروجی ریچ به برنامه خودتان، شما می توانید اضافه (Import)
برای اضافه کردن راحت خروجی ریچ به برنامه خودتان، شما می توانید [rich print](https://rich.readthedocs.io/en/latest/introduction.html#quick-start) را به پروژه خودتان اضافه (Import) کنید که رفتار یکسانی مشابه تابع داخلی پایتون دارد. این را امتحان کنید:

2022-05-08 20:40 UTC, Msameim181 commented on README.fa.md
> +این یک مثال از استفاده Console است:
کد زیر یک مثال از استفاده آن است:

2022-05-08 20:43 UTC, Msameim181 commented on README.fa.md
> +برای اضافه کردن راحت خروجی ریچ به برنامه خودتان، شما می توانید اضافه (Import)
I Just changed the combination and the sequence of words to make it better in looks and understanding.

2022-05-08 20:50 UTC, Msameim181 commented on README.fa.md
> +این را امتحان کنید:
```suggestion
برای اضافه کردن راحت خروجی ریچ به برنامه خودتان، شما می توانید 
[rich print](https://rich.readthedocs.io/en/latest/introduction.html#quick-start)
را به پروژه خودتان اضافه (Import) کنید که اثر یکسانی مشابه تابع داخلی پایتون دارد. 
این قطعه کد را امتحان کنید:
```

2022-05-08 20:51 UTC, Msameim181 commented on README.fa.md
> +این یک مثال از استفاده Console است:
```suggestion
کد زیر یک مثال از استفاده آن است:
```

2022-05-08 20:53 UTC, Msameim181 commented on README.fa.md
> +چاپ کند.
```suggestion
همانطور که احتمالا انتظار داشتید، این کد در ترمینال `"Hello World!"` چاپ می کند.
```

2022-05-08 20:55 UTC, Msameim181 commented on README.fa.md
> +توجه کنید که این شبیه به تابع `print`
```suggestion
در نظر داشته باشید که این شبیه به تابع `print`
```

2022-05-08 20:59 UTC, Msameim181 commented on README.fa.md
> +داخلی پایتون به شکل کلمه‌ای نیست.
```suggestion
ریچ متن شما را به صورت کلمه‌ای (واژه بندی شده) در نظر میگیرد تا در عرض (width) ترمینال قرار گیرد.
```

2022-05-08 21:05 UTC, Msameim181 commented on README.fa.md
> +اینجا یک مثال هست:
```suggestion
شما می توانید با اضافه کردن کلمه کلیدی `style` برای خروجی های خود سبک و استایل در نظر بگیرید.
کد زیر مثال استفاده از آن است:
```

2022-05-08 21:07 UTC, Msameim181 commented on README.fa.md
> +این برای سبک دادن به یک خط در زمان کمی خوب است.
```suggestion
تا اینجا برای سبک و استایل دادن به یک خط خوب است.
```

2022-05-08 21:11 UTC, Msameim181 commented on README.fa.md
> +برای جزئیات بیشتر به [Console API](https://rich.readthedocs.io/en/latest/console.html) مراجعه کنید.
```suggestion
شما می توانید از یک شیء Console برای تولید خروجی پیچیده، با کمترین تلاش استفاده کنید. برای جزئیات بیشتر به 
[Console API](https://rich.readthedocs.io/en/latest/console.html) 
مراجعه کنید.
```

2022-05-08 21:13 UTC, Msameim181 commented on README.fa.md
> +را تولید کند.
```suggestion
ریچ دارای یک تابع `inspect`
است که می تواند یک گزارش از هر شیء از پایتون، مثل کلاس (Class)، نمونه (Instance) یا توابع (Builtin) را تولید کند.
```

2022-05-08 21:18 UTC, Msameim181 commented on README.fa.md
> +کد خودتان کمک می کند.
```suggestion
ریچ شامل تعدادی از توابع _قابل اجرا_ داخلی است که شما می توانید برای ایجاد خروجی برازنده و مناسب در ترمینال (CLI) خود استفاده کنید و به شما برای تصحیح (Debug) کد کمک می کند.
```

2022-05-08 21:19 UTC, Msameim181 commented on README.fa.md
> +برای جزییات بیشتز کلیک کنید:
```suggestion
برای جزییات بیشتر روی سر فصل های زیر کلیک کنید:
```

2022-05-08 21:26 UTC, Msameim181 commented on README.fa.md
> +اما همچنان یک ستون برای الان رندر می کند و فایل و خط که کد را تولید کرده است.
```suggestion
شیء Console دارای یک تابع `()log` است که رفتاری مشابه `()print` دارد، اما همچنین یک ستون برای نمایش زمان، فایل مربوطه و شماره خطِ کدِ اجرا شده در نظر می گیرد.
```

2022-05-08 21:30 UTC, Msameim181 commented on README.fa.md
> +repr.
```suggestion
به صورت پیشفرض، ریچ علائم (syntax) را برای ساختار های پایتون و برای رشته (String) های repr برجسته می کند.
```

2022-05-08 21:32 UTC, Msameim181 commented on README.fa.md
> +این یک مثال از برخی ویژگی های آن است:
```suggestion
مثال زیر نمایش برخی ویژگی های آن است:
```

2022-05-08 21:33 UTC, Msameim181 commented on README.fa.md
> +در بالا خروجی زیر را دریافت می کنید:
```suggestion
قطعه کد بالا، خروجی زیر را تولد می کند:
```

2022-05-08 21:38 UTC, Msameim181 commented on README.fa.md
> +صدا زده می شود.
```suggestion
به متغیر های `log_locals` توجه کنید، جایی که تابع log صدا زده می شود، یک جدول که شامل متغیر های محلی است در خروجی نمایش داده می شود.
```

Interpretive translation.

2022-05-08 21:44 UTC, Msameim181 commented on README.fa.md
> +اما یک کمک برای تصحیح برخی از خطاهای برنامه است.
```suggestion
تابع log میتواند برای گزارش گیری در ترمینال برای برنامه هایی با اجراهای طولانی مدت، مثل سرور استفاده شود؛ اما همچنین کمک بسیار مناسب و خوبی برای تصحیح (debugging) برخی خطاهاست.
```

2022-05-08 21:51 UTC, Msameim181 requested changes
قسمت هایی که اصلاح کردم از نظر ترجمه مقداری ضعیف بودن و باعث ابهام در ذهن خواننده و سختی میشد. پیشنهاد میکنم بررسی و تایید بشن. 
تا قسمتی بررسی شد، بقیه ش هم در اولین فرصت بررسی میکنم.
پ.ن: گاها برای ترجمه لازمه تا موضوع حفظ بشه و گاهی لازمه که تا مطلب به شکل تفسیری ترجمه بشه.

I Just Correct some minor issues that I noticed so far. Up to line 245 was reviewed. I will resume reviewing as soon as possible.

2022-05-09 05:33 UTC, motahharm commented
@Msameim181 
Thanks for your help, these suggestions were really good.

2022-05-10 08:40 UTC, Msameim181 commented on README.fa.md
> +شما می توانید از
```suggestion
همچنین شما می توانید از
```

2022-05-10 08:53 UTC, Msameim181 commented on README.fa.md
> +های داخلی برای اصلاح و رنگی کردن خروجی از ماژول گزارش پایتون
```suggestion
های داخلی برای فرمت دادن و رنگی کردن خروجی از ماژول گزارش پایتون
```

2022-05-10 11:03 UTC, Msameim181 commented on README.fa.md
> +این یک مثال از خروجی را نشان می دهد:
```suggestion
کد زیر یک مثال از خروجی را نشان می دهد:
```

2022-05-10 11:10 UTC, Msameim181 commented on README.fa.md
> +این یک مثال است:
```suggestion
قطعه کد زیر مثال آن است:
```

2022-05-10 11:12 UTC, Msameim181 commented on README.fa.md
> +Please use this feature wisely.
```suggestion
لطفا از این ویژگی خردمندانه و عاقلانه استفاده کنید.
```

2022-05-10 11:16 UTC, Msameim181 commented on README.fa.md
> +با کارکتر های یونیکد بسازد.
```suggestion
ریچ توانایی آن را دارد که [جداول](https://rich.readthedocs.io/en/latest/tables.html) انعطاف پذیری را با کارکتر های یونیکد (unicode) بسازد.
```

2022-05-10 11:17 UTC, Msameim181 commented on README.fa.md
> +در دایرکتوری تست ساخته شده است.
```suggestion
در دایرکتوری (پوشه) تست ساخته شده است.
```

2022-05-10 11:18 UTC, Msameim181 commented on README.fa.md
> +ارائه می شود.
```suggestion
پردازش می شود.
```

2022-05-10 11:21 UTC, Msameim181 commented on README.fa.md
> +این همان مثال با ترمینال کوچکتر است:
```suggestion
این همان مثال با ترمینال کوچکتر از جدول بالاست:
```

2022-05-10 11:23 UTC, Msameim181 commented on README.fa.md
> +که شما می توانید برای پیاده سازی محتوای ریچ خود نیز از آن استفاده کنید.
```suggestion
بنابراین شما می توانید برای پیاده سازی محتوای ریچ خود نیز از آن استفاده کنید.
```

2022-05-10 11:26 UTC, Msameim181 commented on README.fa.md
> +می توانید ریچ را به عنوان کنترل کننده اصلی
```suggestion
شما می توانید ریچ را به عنوان کنترل کننده اصلی 
```

2022-05-10 11:27 UTC, Msameim181 commented on README.fa.md
> +در اینجا این را در مک او اس نمایش می دهد (در لینوکس مشابه این است):
```suggestion
در مک او اس به صورت زیر نمایش داده می شود (در لینوکس نیز مشابه این است):
```

2022-05-10 11:31 UTC, Msameim181 commented on README.fa.md
> +All Rich renderables make use of the [Console Protocol](https://rich.readthedocs.io/en/latest/protocol.html), which you can also use to implement your own Rich content.
```suggestion
```

2022-05-10 11:32 UTC, Msameim181 commented on README.fa.md
> +[syntax](https://rich.readthedocs.io/en/latest/syntax.html)
```suggestion
[syntax highlighting](https://rich.readthedocs.io/en/latest/syntax.html)
```

2022-05-10 11:35 UTC, Msameim181 commented on README.fa.md
> +در اینجا یک مثال است:
```suggestion
استفاده از آن مشابه پردازش markdown هاست؛ یک شی `Syntax` بسازید و آن را برای کنسول چاپ کنید. مثال آن به صورت زیر است:
```

2022-05-10 11:36 UTC, Msameim181 commented on README.fa.md
> +خروجی اند کد چیزی شبیه به این را تولید می کند:
```suggestion
خروجی کد بالا چیزی شبیه به تصویر زیر را تولید می کند:
```

2022-05-10 11:41 UTC, motahharm commented
Hey @Msameim181 

Thank you so much.

Your suggestions help me a lot.

2022-05-10 11:47 UTC, Msameim181 commented
> Hey @Msameim181
> 
> Thank you so much.
> 
> Your suggestions help me a lot.

Yeah sure, but I think you didn't correct or consider some of them. Sincerely, I recommend accepting them too for better improvement. Also, I will finish reviewing by tonight, so you could pass the review.

2022-05-10 16:20 UTC, Msameim181 commented on README.fa.md
> +در اینجا یک مثال است:
```suggestion
ریچ میتواند [markdown](https://rich.readthedocs.io/en/latest/markdown.html) را پردازش کند و کار مناسبی را برای فرمت بندی آن در ترمینال انجام میدهد.

برای پردازش markdown کافی است تا کلاس `Markdown` آنرا فرا خوانی کرده و یک شی از آن را بسازید و متن حاوی markdown  را به آن بدهید. در نهایت آنرا در کنسول و ترمینال چاپ کنید. مثال آن به صورت زیر است:

```

2022-05-10 16:23 UTC, Msameim181 commented on README.fa.md
> +را در ستون ها نمایش می دهد:
```suggestion
تصویر زیر خروجی [columns example](https://github.com/willmcgugan/rich/blob/master/examples/columns.py) است که داده های استخراج شده از یک API را در ستون ها نمایش می دهد:
```

2022-05-10 16:28 UTC, Msameim181 commented on README.fa.md
> +وجود دارد که فهرست دایرکتوری را در ستون ها نمایش می دهد:
```suggestion
ریچ می تواند محتوا را به صورت [columns](https://rich.readthedocs.io/en/latest/columns.html) مرتب با عرض مساوی یا بهینه ارائه دهد. مثال زیر یک شبیه سازی بسیار ابتدایی از دستور `ls` در (مک او اس / لینوکس) است که فهرست دایرکتوری را در ستون ها نمایش می دهد:

```
ریچ می تواند محتوا را به صورت [columns](https://rich.readthedocs.io/en/latest/columns.html) مرتب با عرض مساوی یا بهینه ارائه دهد. مثال زیر یک شبیه سازی بسیار ابتدایی از دستور `ls` در (مک او اس / لینوکس) است که فهرست دایرکتوری را در ستون ها نمایش می دهد:

2022-05-10 16:30 UTC, Msameim181 commented on README.fa.md
> +مثال آن به صورت زیر است:
```suggestion
ریچ از کتابخانه [pygments](https://pygments.org/) برای پیاده سازی[syntax highlighting](https://rich.readthedocs.io/en/latest/syntax.html) استفاده می کند. استفاده از آن مشابه پردازش markdown هاست؛ یک شی `Syntax` بسازید و آن را برای کنسول چاپ کنید. مثال آن به صورت زیر است:
```

ریچ از کتابخانه [pygments](https://pygments.org/) برای پیاده سازی[syntax highlighting](https://rich.readthedocs.io/en/latest/syntax.html) استفاده می کند. استفاده از آن مشابه پردازش markdown هاست؛ یک شی `Syntax` بسازید و آن را برای کنسول چاپ کنید. مثال آن به صورت زیر است:

2022-05-10 16:31 UTC, Msameim181 commented on README.fa.md
> +تنظیم کنید تا همه استثناهای کشف نشده توسط ریچ ارائه شوند.
```suggestion
ریچ می تواند [tracebacks](https://rich.readthedocs.io/en/latest/traceback.html) های زیبایی را نمایش دهد که خواندن آن آسان تر است و کد بیشتری را نسبت به `traceback` های استاندارد پایتون نشان می دهد. شما می توانید ریچ را به عنوان کنترل کننده اصلی `tracebacks` تنظیم کنید تا همه استثناهای کشف نشده توسط ریچ ارائه شوند.
```

ریچ می تواند [tracebacks](https://rich.readthedocs.io/en/latest/traceback.html) های زیبایی را نمایش دهد که خواندن آن آسان تر است و کد بیشتری را نسبت به `traceback` های استاندارد پایتون نشان می دهد. شما می توانید ریچ را به عنوان کنترل کننده اصلی `tracebacks` تنظیم کنید تا همه استثناهای کشف نشده توسط ریچ ارائه شوند.

2022-05-10 16:35 UTC, Msameim181 commented on README.fa.md
> +در لینوکس است.
```suggestion
مثال [tree.py](https://github.com/willmcgugan/rich/blob/master/examples/tree.py) را برای اسکریپتی ببینید که نمایش درختی از هر دایرکتوری را نمایش می دهد، شبیه به فرمان `tree` در لینوکس است.
```
مثال [tree.py](https://github.com/willmcgugan/rich/blob/master/examples/tree.py) را برای اسکریپتی ببینید که نمایش درختی از هر دایرکتوری را نمایش می دهد، شبیه به فرمان `tree` در لینوکس است.

2022-05-10 16:40 UTC, Msameim181 commented on README.fa.md
> +یک چرخنده را انتخاب کنید. برای مشاهده دستور زیر را اجرا کنید:
```suggestion
در انیمیشن های چرخنده از [cli-spinners](https://www.npmjs.com/package/cli-spinners) استفاده شده است. شما می توانید با تعیین پارامتر `spinner` یک چرخنده را انتخاب کنید. برای مشاهده موارد موجود، دستور زیر را اجرا کنید:
```

در انیمیشن های چرخنده از [cli-spinners](https://www.npmjs.com/package/cli-spinners) استفاده شده است. شما می توانید با تعیین پارامتر `spinner` یک چرخنده را انتخاب کنید. برای مشاهده موارد موجود، دستور زیر را اجرا کنید:

2022-05-10 16:43 UTC, Msameim181 commented on README.fa.md
> +را نمایش می‌دهد. این انیمیشن شما را از استفاده عادی از کنسول باز نمی دارد. در اینجا یک مثال است:
```suggestion
برای موقعیت هایی که محاسبه پیشرفت، دشوار است، می توانید از روش [status](https://rich.readthedocs.io/en/latest/reference/console.html#rich.console.Console.status) استفاده کنید که یک پیام و یک انیمیشن چرخنده (spinner) را نمایش می‌دهد. این انیمیشن شما را از استفاده عادی از کنسول باز نمی دارد. مثال آن به صورت زیر است:
```

برای موقعیت هایی که محاسبه پیشرفت، دشوار است، می توانید از روش [status](https://rich.readthedocs.io/en/latest/reference/console.html#rich.console.Console.status) استفاده کنید که یک پیام و یک انیمیشن چرخنده (spinner) را نمایش می‌دهد. این انیمیشن شما را از استفاده عادی از کنسول باز نمی دارد. مثال آن به صورت زیر است:

2022-05-10 16:45 UTC, Msameim181 commented on README.fa.md
> +را به طور همزمان بارگیری کند و پیشرفت را نشان دهد.
```suggestion
برای اینکه خودتان این را امتحان کنید، فایل [examples/downloader.py](https://github.com/willmcgugan/rich/blob/master/examples/downloader.py) را ببینید که می‌تواند چندین لینک URL را به طور همزمان بارگیری کند و پیشرفت را نشان دهد.
```

برای اینکه خودتان این را امتحان کنید، فایل [examples/downloader.py](https://github.com/willmcgugan/rich/blob/master/examples/downloader.py) را ببینید که می‌تواند چندین لینک URL را به طور همزمان بارگیری کند و پیشرفت را نشان دهد.

2022-05-10 16:57 UTC, Msameim181 commented on README.fa.md
> +روی نتیجه تکرار کنید. در اینجا یک مثال است:
```suggestion
ریچ می تواند چندین نوار پیشرفت ([progress](https://rich.readthedocs.io/en/latest/progress.html)) را بدون ناهماهنگی و اختلال برای پیگیری وظایف طولانی مدت پردازش کند.

برای استفاده اولیه، هر دنباله ای را در تابع `track` بسته بندی کنید و روی نتیجه تکرار کنید. مثال آن به صورت زیر است:
```
ریچ می تواند چندین نوار پیشرفت ([progress](https://rich.readthedocs.io/en/latest/progress.html)) را بدون ناهماهنگی و اختلال برای پیگیری وظایف طولانی مدت پردازش کند.

برای استفاده اولیه، هر دنباله ای را در تابع `track` بسته بندی کنید و روی نتیجه تکرار کنید. مثال آن به صورت زیر است:

2022-05-10 16:59 UTC, Msameim181 commented on README.fa.md
> +این همان مثال با ترمینال کوچکتر از جدول بالاست:
```suggestion
توجه داشته باشید که نشانه گذاری کنسول به همان روش  `print()` و `log()` پردازش می شود. در واقع، هر چیزی که توسط Rich قابل رندر است در هدرها / ردیف ها (حتی جداول دیگر) ممکن است گنجانده شود.

کلاس `Table` به اندازه کافی هوشمند است که اندازه ستون ها را متناسب با عرض موجود ترمینال تغییر دهد و متن را در صورت لزوم بسته بندی کند. این همان مثال با ترمینال کوچکتر از جدول بالاست:
```

توجه داشته باشید که نشانه گذاری کنسول به همان روش  `()print` و `()log` پردازش می شود. در واقع، هر چیزی که توسط Rich قابل رندر است در هدرها / ردیف ها (حتی جداول دیگر) ممکن است گنجانده شود.

کلاس `Table` به اندازه کافی هوشمند است که اندازه ستون ها را متناسب با عرض موجود ترمینال تغییر دهد و متن را در صورت لزوم بسته بندی کند. این همان مثال با ترمینال کوچکتر از جدول بالاست:

2022-05-10 17:03 UTC, Msameim181 commented on README.fa.md
> +برخی خطاهاست.
```suggestion
به متغیر های `log_locals` توجه کنید، جایی که تابع log صدا زده می شود، یک جدول که شامل متغیر های محلی است در خروجی نمایش داده می شود.

تابع log میتواند برای گزارش گیری در ترمینال برای برنامه هایی با اجراهای طولانی مدت، مثل سرور استفاده شود؛ اما همچنین کمک بسیار مناسب و خوبی برای تصحیح (debugging) برخی خطاهاست.
```

به متغیر های `log_locals` توجه کنید، جایی که تابع log صدا زده می شود، یک جدول که شامل متغیر های محلی است در خروجی نمایش داده می شود.

تابع log میتواند برای گزارش گیری در ترمینال برای برنامه هایی با اجراهای طولانی مدت، مثل سرور استفاده شود؛ اما همچنین کمک بسیار مناسب و خوبی برای تصحیح (debugging) برخی خطاهاست.

2022-05-10 17:05 UTC, Msameim181 commented on README.fa.md
> +مثال زیر نمایش برخی ویژگی های آن است:
```suggestion
شیء Console دارای یک تابع `()log` است که رفتاری مشابه `()print` دارد، اما همچنین یک ستون برای نمایش زمان، فایل مربوطه و شماره خطِ کدِ اجرا شده در نظر می گیرد. به صورت پیشفرض، ریچ علائم (syntax) را برای ساختار های پایتون و برای رشته (String)
های repr برجسته می کند. اگر شما یک مجموعه (دیکشنری یا لیست) را چاپ کنید، ریچ به زیبایی آن را در فضای موجود چاپ می کند. مثال زیر نمایش برخی ویژگی های آن است:
```

شیء Console دارای یک تابع `()log` است که رفتاری مشابه `()print` دارد، اما همچنین یک ستون برای نمایش زمان، فایل مربوطه و شماره خطِ کدِ اجرا شده در نظر می گیرد. به صورت پیشفرض، ریچ علائم (syntax) را برای ساختار های پایتون و برای رشته (String)
های repr برجسته می کند. اگر شما یک مجموعه (دیکشنری یا لیست) را چاپ کنید، ریچ به زیبایی آن را در فضای موجود چاپ می کند. مثال زیر نمایش برخی ویژگی های آن است:

2022-05-10 17:06 UTC, Msameim181 commented on README.fa.md
> +کد کمک می کند.
```suggestion
ریچ شامل تعدادی از توابع _قابل اجرا_ داخلی است که شما می توانید برای ایجاد خروجی برازنده و مناسب در ترمینال (CLI) خود استفاده کنید و به شما برای تصحیح (Debug) کد کمک می کند.
```

ریچ شامل تعدادی از توابع _قابل اجرا_ داخلی است که شما می توانید برای ایجاد خروجی برازنده و مناسب در ترمینال (CLI) خود استفاده کنید و به شما برای تصحیح (Debug) کد کمک می کند.

2022-05-10 17:08 UTC, Msameim181 commented on README.fa.md
> +را تولید کند.
```suggestion
ریچ دارای یک تابع `inspect` است که می تواند یک گزارش از هر شیء از پایتون، مثل کلاس (Class)، نمونه (Instance) یا توابع (Builtin) را تولید کند.
```

ریچ دارای یک تابع `inspect` است که می تواند یک گزارش از هر شیء از پایتون، مثل کلاس (Class)، نمونه (Instance) یا توابع از پیش ساخته (Builtin) را تولید کند.

2022-05-10 17:16 UTC, Msameim181 requested changes
I'm Done Changing :). It's Completed now. Please review the changes so we could go to the next step.

Also, You forgot to add 'Rich CLI', 'Textual', and 'Projects using Rich' parts. If you add it would be nice.

2022-05-10 17:56 UTC, motahharm reviewed
It's good

2022-05-11 06:35 UTC, motahharm commented
@Msameim181 Thanks for the review.

I added 'Rich CLI', 'Textual', and 'Projects using Rich' to README.fa.md.

2022-05-11 07:15 UTC, Msameim181 commented on README.fa.md
> +برجسته سازی کد، رندر کردن مارک دون، نمایش فایل های CSV در جدول ها، و غیره... ، به صورت مستقیم از خط فرمان.
```suggestion
همچنین [Rich CLI](https://github.com/textualize/rich-cli) را که برای برنامه های دستوری (command line)، توسط Rich ساخته شده است ببینید. برجسته سازی کد (Syntax highlight code)، پردازش کردن مارک دون، نمایش فایل های CSV در جدول ها و موارد بیشتر، به صورت مستقیم از خط فرمان و ترمینال.
```

همچنین [Rich CLI](https://github.com/textualize/rich-cli) را که برای برنامه های دستوری (command line)، توسط Rich ساخته شده است ببینید. برجسته سازی کد (Syntax highlight code)، پردازش کردن مارک دون، نمایش فایل های CSV در جدول ها و موارد بیشتر، به صورت مستقیم از خط فرمان و ترمینال.

2022-05-11 07:17 UTC, Msameim181 commented on README.fa.md
> +همچنین ببینید پروژه خواهر ریچ [Textual](https://github.com/Textualize/textual)، که با استفاده از آن شما می توانید رابط های کاربری پیچیده را در ترمینال بسازید.
```suggestion
همچنین (پروژه) خواهر ریچ [Textual](https://github.com/Textualize/textual) را ببینید، که با استفاده از آن شما می توانید رابط های کاربری پیچیده را در ترمینال بسازید.
```
همچنین (پروژه) خواهر ریچ [Textual](https://github.com/Textualize/textual) را ببینید، که با استفاده از آن شما می توانید رابط های کاربری پیچیده را در ترمینال بسازید.

2022-05-11 07:19 UTC, Msameim181 commented on README.fa.md
> +[این کار ها را](https://www.textualize.io/gallery-instructions) انجام دهید.
```suggestion
برای دیدن چند نمونه از پروژه هایی که از ریچ استفاده می کنند، به [Rich Gallery](https://www.textualize.io/rich/gallery) در [Textualize.io](https://www.textualize.io) سر بزنید.

آیا می خواهید پروژه خودتان را به گالری اضافه کنید؟ شما می توانید! کافیست [از این دستورات](https://www.textualize.io/gallery-instructions) پیروی کنید.
```

برای دیدن چند نمونه از پروژه هایی که از ریچ استفاده می کنند، به [Rich Gallery](https://www.textualize.io/rich/gallery) در [Textualize.io](https://www.textualize.io) سر بزنید.

آیا می خواهید پروژه خودتان را به گالری اضافه کنید؟ شما می توانید! کافیست [از این دستورات](https://www.textualize.io/gallery-instructions) پیروی کنید.

2022-05-11 07:21 UTC, Msameim181 commented
> @Msameim181 Thanks for the review.
> 
> I added 'Rich CLI', 'Textual', and 'Projects using Rich' to README.fa.md.

Your welcome, Yeah I checked it. It seems we are done. Almost.

2022-05-11 07:33 UTC, Msameim181 approved these changes
After many changes and improvements, I Approve it as a native Persian.

2022-05-11 07:34 UTC, Msameim181 approved these changes

2022-05-11 08:18 UTC, motahharm commented
> After many changes and improvements, I Approve it as a native Persian.

many thanks @Msameim181 

so it's done✅

2022-06-14 08:17 UTC, willmcgugan commented
Thanks a lot!

2022-06-14 08:17 UTC, willmcgugan approved these changes

2022-06-14 08:17 UTC, merged