Add Iso8601Highlighter
Textualize/rich pull request #2301
Opened 2022-05-26 19:09 UTC by tomers

## Type of changes

- [ ] Bug fix
- [X] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [X] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [X] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [X] I've added tests for new code.
- [X] I accept that @willmcgugan may be pedantic in the code review.

## Description

As suggesterd by @willmcgugan in #2295, I've added a date-time highlighter.

2022-06-14 08:36 UTC, willmcgugan requested changes
This is great. Could you add something to the docs (probably in the highlighter section).

2022-06-14 08:36 UTC, willmcgugan commented on rich/highlighter.py
> +class Iso8601Highlighter(RegexHighlighter):
I think camel case would require it to be `ISO8601Highlighter`

2022-06-14 11:35 UTC, tomers commented
@willmcgugan, I've force-pushed without realizing that you submitted to the remote branch. Can you re-introduce your changes? Sorry for that.

2022-06-21 11:36 UTC, tomers commented
@willmcgugan, what else need to be done in order for this to be merged?

2022-07-11 10:46 UTC, willmcgugan commented
Thanks

2022-07-11 10:46 UTC, merged